ALTER TABLE restaurants ADD COLUMN story TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN instagram TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN hours_detail TEXT NOT NULL DEFAULT '';
ALTER TABLE restaurants ADD COLUMN promo TEXT NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN is_special INTEGER NOT NULL DEFAULT 0;
