/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AdminMenuSettingsRouteImport } from './routes/admin.menu-settings'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as SuperadminBroadcastRouteImport } from './routes/superadmin.broadcast'
import { Route as SuperadminRestaurantsRouteImport } from './routes/superadmin.restaurants'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuSettingsRoute = AdminMenuSettingsRouteImport.update({
  id: '/menu-settings',
  path: '/menu-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminBroadcastRoute = SuperadminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRestaurantsRoute = SuperadminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/menu-settings': typeof AdminMenuSettingsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/superadmin/broadcast': typeof SuperadminBroadcastRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/menu-settings': typeof AdminMenuSettingsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/superadmin/broadcast': typeof SuperadminBroadcastRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/menu-settings': typeof AdminMenuSettingsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/superadmin/broadcast': typeof SuperadminBroadcastRoute
  '/superadmin/restaurants': typeof SuperadminRestaurantsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/superadmin'
    | '/account/settings'
    | '/admin/menu-settings'
    | '/admin/waitlist'
    | '/superadmin/broadcast'
    | '/superadmin/restaurants'
    | '/superadmin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/superadmin'
    | '/account/settings'
    | '/admin/menu-settings'
    | '/admin/waitlist'
    | '/superadmin/broadcast'
    | '/superadmin/restaurants'
    | '/superadmin/users'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/superadmin'
    | '/account/settings'
    | '/admin/menu-settings'
    | '/admin/waitlist'
    | '/superadmin/broadcast'
    | '/superadmin/restaurants'
    | '/superadmin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu-settings': {
      id: '/admin/menu-settings'
      path: '/menu-settings'
      fullPath: '/admin/menu-settings'
      preLoaderRoute: typeof AdminMenuSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/broadcast': {
      id: '/superadmin/broadcast'
      path: '/broadcast'
      fullPath: '/superadmin/broadcast'
      preLoaderRoute: typeof SuperadminBroadcastRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/restaurants': {
      id: '/superadmin/restaurants'
      path: '/restaurants'
      fullPath: '/superadmin/restaurants'
      preLoaderRoute: typeof SuperadminRestaurantsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMenuSettingsRoute: typeof AdminMenuSettingsRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMenuSettingsRoute: AdminMenuSettingsRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperadminRouteChildren {
  SuperadminBroadcastRoute: typeof SuperadminBroadcastRoute
  SuperadminRestaurantsRoute: typeof SuperadminRestaurantsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminBroadcastRoute: SuperadminBroadcastRoute,
  SuperadminRestaurantsRoute: SuperadminRestaurantsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
